### ISSUE TITLE
Test results available?

### ISSUE THREAD

**Issue by uhi22** [Millisman/QCA7000#1]
Hi, great work. Are there test results available? What is the status?
Thanks and have a nice day,
uhi22

**Comment by Millisman** [comment]
Hello! Because of the war, my plans changed. This project is in perpetual archive, but I can complete it commercially.

**Comment by Millisman** [comment]
> Hi, great work. Are there test results available? What is the status? Thanks and have a nice day, uhi22

Hello! Because of the war, my plans changed. This project is in perpetual archive, but I can complete it commercially.
Sounds like you're developing your own battery charge controller?
If done incorrectly, people can get hurt. Be careful.

**Comment by uhi22** [comment]
Hello and thanks. Yes, we are developing an open source charge controller. It is shared here: https://github.com/uhi22/foccci and the discussion happens on the openinverter forum: https://openinverter.org/forum/viewtopic.php?t=3727
Thank you for publishing the draft version.
